### PR TITLE
Remove need for uuid

### PR DESCRIPTION
**Pull request by fonsp**

### CODE REVIEW

**Comment by j-fu** [comment]
Ok this is probably faster as it avoids the id lookup.

**Comment by j-fu** [comment]
Hi, undid the commit due to weird behavior.

Try to lower resolution (e.g. (200,200)) In the second plot. It didn't affect this and  the view kind of jumped to the previous plot.  My impression is that there is some ambiguity with defining what is seen as the previous sibling.  What else is drawback of the uuids  besides slightly slower operation (the ids are hashed anyway in a proper implementation, aren't they ?)

**Comment by fonsp** [comment]
Sorry, I changed the `div` to `span`, but it should have stayed a `div`, otherwise the `width` and `height` style attributes are ignored.

I made the PR not for performance reasons, but more of a "style suggestion".

**Comment by j-fu** [comment]
Yeah, just also figured out that this might have been also  div vs span....

EDIT: still got some ideas where the uuids could be useful, so I will keep them for now...

**Pull request merged**
